In [7]:
# type your code here
# type your code here
# import 'Pandas' 
import pandas as pd 

# import 'Numpy' 
import numpy as np

# import subpackage of Matplotlib
import matplotlib.pyplot as plt

# import 'Seaborn' 
import seaborn as sns

# to suppress warnings 
from warnings import filterwarnings
filterwarnings('ignore')

# display all columns of the dataframe
pd.options.display.max_columns = None

# display all rows of the dataframe
pd.options.display.max_rows = None
 
# to display the float values upto 6 decimal places     
pd.options.display.float_format = '{:.6f}'.format

# import train-test split 
from sklearn.model_selection import train_test_split

# import various functions from statsmodel to perform linear regression
import statsmodels
import statsmodels.api as sm
import statsmodels.stats.api as sms
from statsmodels.compat import lzip
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.graphics.gofplots import qqplot
from statsmodels.stats.anova import anova_lm
from statsmodels.formula.api import ols
from statsmodels.tools.eval_measures import rmse

# import various functions from scipy
from scipy import stats
from scipy.stats import shapiro

# 'metrics' from sklearn is used for evaluating the model performance
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import SGDRegressor

In [8]:
# type your code here
df= pd.read_csv('~/Desktop/New folder (3)/reg take/Day 01/car_data.csv')
# display first five observations using head()
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.350000,5.590000,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.750000,9.540000,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.250000,9.850000,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.850000,4.150000,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.600000,6.870000,42450,Diesel,Dealer,Manual,0

In [9]:
# type your code here'
df.shape

(301, 9)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

In [11]:
df[''].plot(kind = 'hist')

KeyError: ''

In [12]:
df['Seller_Type'].unique()

array(['Dealer', 'Individual'], dtype=object)

In [13]:
# type your code here
y = df['Selling_Price']
df_ = df.drop('Selling_Price',axis = 1)
df_ = df_.drop('Car_Name',axis = 1)
df_ = df_[0:]

df_m = sm.add_constant(df_)
x = pd.get_dummies(df_m,drop_first = True)
model = sm.OLS(y,x).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:          Selling_Price   R-squared:                       0.883
Model:                            OLS   Adj. R-squared:                  0.879
Method:                 Least Squares   F-statistic:                     274.3
Date:                Fri, 05 Aug 2022   Prob (F-statistic):          5.71e-131
Time:                        10:11:23   Log-Likelihood:                -593.62
No. Observations:                 301   AIC:                             1205.
Df Residuals:                     292   BIC:                             1239.
Df Model:                           8
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
const                   -789.2366     86.522     -9.122      0.000    -959.522    -618.951
Year                       0.3931      0.043      9.159      0.000       0.309       0.478
Present_Price              0.4372      0.016     27.355      0.000       0.406       0.469
Kms_Driven             -7.013e-06   3.23e-06     -2.172      0.031   -1.34e-05   -6.57e-07
Owner                     -0.6742      0.423     -1.595      0.112      -1.506       0.158
Fuel_Type_Diesel           2.4699      1.278      1.932      0.054      -0.046       4.986
Fuel_Type_Petrol           0.6077      1.259      0.483      0.630      -1.870       3.085
Seller_Type_Individual    -1.1213      0.257     -4.371      0.000      -1.626      -0.616
Transmission_Manual       -1.4482      0.328     -4.417      0.000      -2.093      -0.803
==============================================================================
Omnibus:                       95.107   Durbin-Watson:                   1.795
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              696.392
Skew:                           1.075   Prob(JB):                    6.03e-152
Kurtosis:                      10.135   Cond. No.                     4.56e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.56e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [14]:
# type your code here
vif = pd.DataFrame()
df_num = df.select_dtypes(include = np.number)
vif['feat'] = df_num.columns
vif['vif'] = [variance_inflation_factor(df_num.values,i)for i in range (df_num.shape[1])]
print(vif)

            feat      vif
0           Year 2.780556
1  Selling_Price 9.355028
2  Present_Price 9.339093
3     Kms_Driven 2.215973
4          Owner 1.074269

In [15]:
# type your code heredf
df_.columns
df1 = df_.iloc[:,[1,4]]
df1 = pd.get_dummies(df1)
y = df['Selling_Price']
df1 = sm.add_constant(df1)
mode = sm.OLS(y,df1).fit()
mode.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:          Selling_Price   R-squared:                       0.786
Model:                            OLS   Adj. R-squared:                  0.785
Method:                 Least Squares   F-statistic:                     548.4
Date:                Fri, 05 Aug 2022   Prob (F-statistic):          1.34e-100
Time:                        10:11:24   Log-Likelihood:                -683.71
No. Observations:                 301   AIC:                             1373.
Df Residuals:                     298   BIC:                             1385.
Df Model:                           2
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
const                      0.5451      0.122      4.474      0.000       0.305       0.785
Present_Price              0.4758      0.018     25.956      0.000       0.440       0.512
Seller_Type_Dealer         0.9972      0.183      5.438      0.000       0.636       1.358
Seller_Type_Individual    -0.4521      0.169     -2.672      0.008      -0.785      -0.119
==============================================================================
Omnibus:                       72.895   Durbin-Watson:                   1.645
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              845.311
Skew:                           0.581   Prob(JB):                    2.77e-184
Kurtosis:                      11.127   Cond. No.                     8.29e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.85e-30. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [17]:
# type your code here
df_['feature']  = df_['Present_Price']*df['Year']
df2 = df_.iloc[:,[0,1]]
y = df['Selling_Price']
df2 = sm.add_constant(df2)
modell = sm.OLS(y,df2).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:          Selling_Price   R-squared:                       0.883
Model:                            OLS   Adj. R-squared:                  0.879
Method:                 Least Squares   F-statistic:                     274.3
Date:                Fri, 05 Aug 2022   Prob (F-statistic):          5.71e-131
Time:                        10:11:25   Log-Likelihood:                -593.62
No. Observations:                 301   AIC:                             1205.
Df Residuals:                     292   BIC:                             1239.
Df Model:                           8
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
const                   -789.2366     86.522     -9.122      0.000    -959.522    -618.951
Year                       0.3931      0.043      9.159      0.000       0.309       0.478
Present_Price              0.4372      0.016     27.355      0.000       0.406       0.469
Kms_Driven             -7.013e-06   3.23e-06     -2.172      0.031   -1.34e-05   -6.57e-07
Owner                     -0.6742      0.423     -1.595      0.112      -1.506       0.158
Fuel_Type_Diesel           2.4699      1.278      1.932      0.054      -0.046       4.986
Fuel_Type_Petrol           0.6077      1.259      0.483      0.630      -1.870       3.085
Seller_Type_Individual    -1.1213      0.257     -4.371      0.000      -1.626      -0.616
Transmission_Manual       -1.4482      0.328     -4.417      0.000      -2.093      -0.803
==============================================================================
Omnibus:                       95.107   Durbin-Watson:                   1.795
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              696.392
Skew:                           1.075   Prob(JB):                    6.03e-152
Kurtosis:                      10.135   Cond. No.                     4.56e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.56e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [18]:
# type your code here
df3 = pd.get_dummies(df_['Fuel_Type'])
df3 = sm.add_constant(df3)
y = df['Selling_Price']
mod1 = sm.OLS(y,df3).fit()
mod1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:          Selling_Price   R-squared:                       0.305
Model:                            OLS   Adj. R-squared:                  0.300
Method:                 Least Squares   F-statistic:                     65.41
Date:                Fri, 05 Aug 2022   Prob (F-statistic):           2.80e-24
Time:                        10:11:25   Log-Likelihood:                -861.21
No. Observations:                 301   AIC:                             1728.
Df Residuals:                     298   BIC:                             1740.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          4.1607      0.767      5.424      0.000       2.651       5.670
CNG           -1.0607      2.260     -0.469      0.639      -5.508       3.387
Diesel         6.1178      0.860      7.117      0.000       4.426       7.810
Petrol        -0.8965      0.791     -1.133      0.258      -2.454       0.661
==============================================================================
Omnibus:                      149.368   Durbin-Watson:                   1.338
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              826.132
Skew:                           2.022   Prob(JB):                    4.05e-180
Kurtosis:                      10.036   Cond. No.                     9.51e+15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.69e-30. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [19]:
# type your code here
df4 = pd.get_dummies(df_['Transmission'])
df4 = sm.add_constant(df4)
y = df['Selling_Price']
mod2 = sm.OLS(y,df4).fit()
mod2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:          Selling_Price   R-squared:                       0.135
Model:                            OLS   Adj. R-squared:                  0.132
Method:                 Least Squares   F-statistic:                     46.58
Date:                Fri, 05 Aug 2022   Prob (F-statistic):           4.90e-11
Time:                        10:11:26   Log-Likelihood:                -894.20
No. Observations:                 301   AIC:                             1792.
Df Residuals:                     299   BIC:                             1800.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          4.4507      0.268     16.604      0.000       3.923       4.978
Automatic      4.9693      0.509      9.769      0.000       3.968       5.970
Manual        -0.5187      0.317     -1.636      0.103      -1.143       0.105
==============================================================================
Omnibus:                      143.925   Durbin-Watson:                   1.182
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              946.055
Skew:                           1.855   Prob(JB):                    3.69e-206
Kurtosis:                      10.853   Cond. No.                     1.55e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.25e-30. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [24]:
# type your code here
y = df['Selling_Price']
x = sm.add_constant(df_['Present_Price'])
mode = sm.OLS(y,x).fit()
mode.summary()
mode.conf_int(alpha = 0.01)

                     0        1
const         0.234343 1.202712
Present_Price 0.474812 0.558886

In [25]:
mode.conf_int(alpha = 0.05)

                     0        1
const         0.350972 1.086083
Present_Price 0.484938 0.548760

In [26]:
# type your code here
y = df['Selling_Price']
x = sm.add_constant(df_['Present_Price'])
mode = sm.OLS(y,x).fit()
mode.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:          Selling_Price   R-squared:                       0.773
Model:                            OLS   Adj. R-squared:                  0.772
Method:                 Least Squares   F-statistic:                     1016.
Date:                Fri, 05 Aug 2022   Prob (F-statistic):           3.60e-98
Time:                        10:17:35   Log-Likelihood:                -693.08
No. Observations:                 301   AIC:                             1390.
Df Residuals:                     299   BIC:                             1398.
Df Model:                           1
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             0.7185      0.187      3.847      0.000       0.351       1.086
Present_Price     0.5168      0.016     31.874      0.000       0.485       0.549
==============================================================================
Omnibus:                       59.775   Durbin-Watson:                   1.533
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              926.121
Skew:                           0.084   Prob(JB):                    7.86e-202
Kurtosis:                      11.592   Cond. No.                         15.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [53]:
sc = StandardScaler()
df_s = pd.get_dummies(df_,drop_first=True)
# dfs = sc.fit_transform(dfs)
df_s

,Year,Present_Price,Kms_Driven,Owner,feature,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,2014,5.590000,27000,0,11258.260000,0,1,0,1
1,2013,9.540000,43000,0,19204.020000,1,0,0,1
2,2017,9.850000,6900,0,19867.450000,0,1,0,1
3,2011,4.150000,5200,0,8345.650000,0,1,0,1
4,2014,6.870000,42450,0,13836.180000,1,0,0,1
5,2018,9.830000,2071,0,19836.940000,1,0,0,1
6,2015,8.120000,18796,0,16361.800000,0,1,0,1
7,2015,8.610000,33429,0,17349.150000,1,0,0,1
8,2016,8.890000,20273,0,17922.240000,1,0,0,1
9,2015,8.920000,42367,0,17973.800000,1,0,0,1
10,2017,3.600000,2135,0,7261.200000,0,1,0,1
11,2015,10.380000,51000,0,20915.700000,1,0,0,1
12,2015,9.940000,15000,0,20029.100000,0,1,0,0
13,2015,7.710000,26000,0,15535.650000,0,1,0,1
14,2009,7.210000,77427,0,14484.890000,0,1,0,1
15,2016,10.790000,43000,0,21752.640000,1,0,0,1
16,2015,10.790000,41678,0,21741.850000,1,0,0,1
17,2016,10.790000,43000,0,21752.640000,1,0,0,1
18,2015,5.090000,35500,0,10256.350000,0,0,0,1
19,2010,7.980000,41442,0,16039.800000,0,1,0,1
20,2016,3.950000,25000,0,7963.200000,0,1,0,1
21,2017,5.710000,2400,0,11517.070000,0,1,0,1
22,2011,8.010000,50000,0,16108.110000,0,1,0,0
23,2014,3.460000,45280,0,6968.440000,0,1,0,1
24,2013,4.410000,56879,0,8877.330000,0,1,0,1
25,2011,4.990000,20000,0,10034.890000,0,1,0,1
26,2013,5.870000,55138,0,11816.310000,0,1,0,1
27,2017,6.490000,16200,0,13090.330000,0,1,1,1
28,2010,3.950000,44542,0,7939.500000,0,1,0,1
29,2015,10.380000,45000,0,20915.700000,1,0,0,1
30,2012,5.980000,51439,0,12031.760000,1,0,0,1
31,2011,4.890000,54200,0,9833.790000,0,1,0,1
32,2014,7.490000,39000,0,15084.860000,1,0,0,1
33,2014,9.950000,45000,0,20039.300000,1,0,0,1
34,2014,8.060000,45000,0,16232.840000,1,0,0,1
35,2011,7.740000,49998,0,15565.140000,0,0,0,1
36,2015,7.200000,48767,0,14508.000000,0,1,0,1
37,2003,2.280000,127000,0,4566.840000,0,1,1,1
38,2016,3.760000,10079,0,7580.160000,0,1,0,1
39,2003,7.980000,62000,0,15983.940000,0,1,0,1
40,2016,7.870000,24524,0,15865.920000,0,1,0,0
41,2014,3.980000,46706,0,8015.720000,0,1,0,1
42,2008,7.150000,58000,0,14357.200000,0,1,0,1
43,2014,8.060000,45780,0,16232.840000,1,0,0,1
44,2012,2.690000,50000,0,5412.280000,0,1,0,1
45,2014,12.040000,15000,0,24248.560000,0,1,0,0
46,2013,4.890000,64532,0,9843.570000,0,1,0,1
47,2006,4.150000,65000,0,8324.900000,0,1,0,1
48,2015,7.710000,25870,0,15535.650000,0,1,0,1
49,2017,9.290000,37000,0,18737.930000,0,1,0,0
50,2012,30.610000,104707,0,61587.320000,1,0,0,0
51,2015,30.610000,40000,0,61679.150000,1,0,0,0
52,2017,19.770000,15000,0,39876.090000,1,0,0,0
53,2013,30.610000,135000,0,61617.930000,1,0,1,0
54,2005,10.210000,90000,0,20471.050000,0,1,1,1
55,2009,15.040000,70000,0,30215.360000,0,1,0,0
56,2015,7.270000,40534,0,14649.050000,0,1,0,1
57,2010,18.540000,50000,0,37265.400000,0,1,0,1
58,2014,6.800000,39485,1,13695.200000,0,1,0,1
59,2014,35.960000,41000,0,72423.440000,1,0,0,0
60,2013,18.610000,40001,0,37461.930000,0,1,0,1
61,2015,7.700000,40588,0,15515.500000,0,1,0,1
62,2014,35.960000,78000,0,72423.440000,1,0,0,0
63,2015,35.960000,47000,0,72459.400000,1,0,0,0
64,2017,36.230000,6000,0,73075.910000,1,0,0,0
65,2014,6.950000,45000,0,13997.300000,1,0,0,1
66,2017,23.150000,11000,0,46693.550000,0,1,0,0
67,2010,20.450000,59000,0,41104.500000,1,0,0,1
68,2011,13.740000,88000,0,27631.140000,0,1,0,1
69,2016,20.910000,12000,0,42154.560000,0,1,0,1
70,2014,6.760000,71000,0,13614.640000,1,0,0,1
71,2011,12.480000,45000,0,25097.280000,1,0,0,1
72,2013,18.610000,56001,0,37461.930000,0,1,0,1
73,2011,5.710000,43000,0,11482.810000,0,1,0,1
74,2014,8.930000,83000,0,17985.020000,1,0,0,1
75,2015,6.800000,36000,0,13702.000000,0,1,0,1
76,2013,14.680000,72000,0,29550.840000,0,1,0,1
77,2004,12.350000,135154,0,24749.400000,0,1,0,0
78,2010,22.830000,80000,0,45888.300000,0,1,0,0
79,2012,30.610000,89000,0,61587.320000,1,0,0,0
80,2016,14.890000,23000,0,30018.240000,1,0,0,1
81,2015,7.850000,40000,0,15817.750000,1,0,0,1
82,2017,25.390000,15000,0,51211.630000,1,0,0,0
83,2015,13.460000,38000,0,27121.900000,1,0,0,1
84,2005,13.460000,197176,0,26987.300000,1,0,0,1
85,2006,23.730000,142000,3,47602.380000,0,1,1,0
86,2010,92.600000,78000,0,186126.000000,1,0,0,1
87,2012,13.740000,56000,0,27644.880000,0,1,0,1
88,2013,6.050000,47000,0,12178.650000,0,1,0,1
89,2014,6.760000,40000,0,13614.640000,0,1,0,1
90,2009,18.610000,62000,0,37387.490000,0,1,0,1
91,2014,16.090000,58242,0,32405.260000,1,0,0,1
92,2005,13.700000,75000,0,27468.500000,0,1,0,1
93,2015,30.610000,40000,0,61679.150000,1,0,0,0
94,2008,22.780000,89000,0,45742.240000,0,1,0,0
95,2012,18.610000,72000,0,37443.320000,0,1,0,1
96,2016,25.390000,29000,0,51186.240000,1,0,0,0
97,2017,18.640000,8700,0,37596.880000,0,1,0,1
98,2013,18.610000,45000,0,37461.930000,0,1,0,1
99,2010,20.450000,50024,0,41104.500000,1,0,0,1
100,2016,1.900000,3000,0,3830.400000,0,1,1,1
101,2017,1.820000,1400,0,3670.940000,0,1,1,1
102,2017,1.780000,4000,0,3590.260000,0,1,1,1
103,2017,1.600000,1200,0,3227.200000,0,1,1,1
104,2017,1.470000,4100,0,2964.990000,0,1,1,1
105,2015,2.370000,21700,0,4775.550000,0,1,1,1
106,2014,3.450000,16500,1,6948.300000,0,1,1,1
107,2013,1.500000,15000,0,3019.500000,0,1,1,1
108,2016,1.500000,18000,0,3024.000000,0,1,1,1
109,2017,1.470000,11000,0,2964.990000,0,1,1,1
110,2016,1.780000,6000,0,3588.480000,0,1,1,1
111,2016,1.500000,8700,0,3024.000000,0,1,1,1
112,2014,2.400000,7000,0,4833.600000,0,1,1,1
113,2016,1.400000,35000,0,2822.400000,0,1,1,1
114,2015,1.470000,17000,0,2962.050000,0,1,1,1
115,2015,1.470000,17500,0,2962.050000,0,1,1,1
116,2013,1.470000,33000,0,2959.110000,0,1,1,1
117,2015,1.900000,14000,0,3828.500000,0,1,1,1
118,2015,1.470000,26000,0,2962.050000,0,1,1,1
119,2013,1.900000,5400,0,3824.700000,0,1,1,1
120,2016,1.260000,5700,0,2540.160000,0,1,1,1
121,2011,1.500000,6900,0,3016.500000,0,1,1,1
122,2016,1.170000,6000,0,2358.720000,0,1,1,1
123,2013,1.470000,46500,0,2959.110000,0,1,1,1
124,2012,1.750000,11500,0,3521.000000,0,1,1,1
125,2009,1.750000,40000,0,3515.750000,0,1,1,1
126,2017,0.950000,1300,0,1916.150000,0,1,1,1
127,2016,0.800000,7000,0,1612.800000,0,1,1,1
128,2017,0.870000,3000,0,1754.790000,0,1,1,1
129,2017,0.840000,5000,0,1694.280000,0,1,1,1
130,2017,0.870000,11000,0,1754.790000,0,1,1,1
131,2015,0.820000,18000,0,1652.300000,0,1,1,1
132,2017,0.950000,3500,0,1916.150000,0,1,1,1
133,2016,0.950000,500,0,1915.200000,0,1,1,1
134,2017,0.810000,11800,0,1633.770000,0,1,1,1
135,2015,0.740000,5000,0,1491.100000,0,1,1,1
136,2014,1.200000,23500,0,2416.800000,0,1,1,1
137,2013,0.787000,16000,0,1584.231000,0,1,1,1
138,2016,0.870000,15000,0,1753.920000,0,1,1,1
139,2015,0.950000,16600,0,1914.250000,0,1,1,1
140,2013,1.200000,32000,0,2415.600000,0,1,1,1
141,2016,0.800000,20000,0,1612.800000,0,1,1,1
142,2015,0.840000,29000,0,1692.600000,0,1,1,1
143,2016,0.840000,25000,0,1693.440000,0,1,1,1
144,2014,0.990000,25000,0,1993.860000,0,1,1,1
145,2012,0.810000,19000,0,1629.720000,0,1,1,1
146,2014,0.787000,15000,0,1585.018000,0,1,1,1
147,2015,0.840000,58000,0,1692.600000,0,1,1,1
148,2010,0.940000,45000,0,1889.400000,0,1,1,1
149,2016,0.940000,24000,0,1895.040000,0,1,1,1
150,2011,0.826000,6000,0,1661.086000,0,1,1,1
151,2016,0.550000,31000,0,1108.800000,0,1,1,1
152,2012,0.990000,13000,0,1991.880000,0,1,1,1
153,2013,0.990000,45000,0,1992.870000,0,1,1,1
154,2014,0.880000,8000,0,1772.320000,0,1,1,1
155,2017,0.510000,4300,0,1028.670000,0,1,1,0
156,2017,0.520000,15000,0,1048.840000,0,1,1,1
157,2015,0.840000,23000,0,1692.600000,0,1,1,1
158,2017,0.540000,8600,0,1089.180000,0,1,1,1
159,2017,0.510000,4000,0,1028.670000,0,1,1,0
160,2011,0.950000,24000,0,1910.450000,0,1,1,1
161,2014,0.826000,23000,0,1663.564000,0,1,1,1
162,2012,0.990000,14500,0,1991.880000,0,1,1,1
163,2010,0.950000,27000,0,1909.500000,0,1,1,1
164,2016,0.540000,14000,0,1088.640000,0,1,1,1
165,2016,0.540000,500,0,1088.640000,0,1,1,0
166,2016,0.550000,1000,0,1108.800000,0,1,1,1
167,2014,0.810000,42000,0,1631.340000,0,1,1,1
168,2013,0.730000,12000,0,1469.490000,0,1,1,1
169,2015,0.540000,14000,0,1088.100000,0,1,1,1
170,2012,0.830000,5500,0,1669.960000,0,1,1,1
171,2015,0.550000,6700,0,1108.250000,0,1,1,1
172,2014,0.640000,13700,0,1288.960000,0,1,1,1
173,2017,0.510000,1300,0,1028.670000,0,1,1,0
174,2015,0.720000,38600,0,1450.800000,0,1,1,1
175,2011,0.787000,75000,0,1582.657000,0,1,1,1
176,2011,1.050000,30000,0,2111.550000,0,1,1,1
177,2016,0.570000,24000,0,1149.120000,0,1,1,0
178,2014,0.520000,19000,0,1047.280000,0,1,1,0
179,2010,1.050000,213000,0,2110.500000,0,1,1,1
180,2012,0.510000,60000,0,1026.120000,0,1,1,1
181,2016,0.480000,50000,0,967.680000,0,1,1,1
182,2013,0.580000,30000,0,1167.540000,0,1,1,1
183,2013,0.470000,21000,0,946.110000,0,1,1,1
184,2008,0.750000,26000,1,1506.000000,0,1,1,1
185,2008,0.580000,1900,0,1164.640000,0,1,1,0
186,2010,0.520000,22000,0,1045.200000,0,1,1,0
187,2013,0.510000,32000,0,1026.630000,0,1,1,1
188,2013,0.570000,18000,0,1147.410000,0,1,1,1
189,2005,0.570000,55000,0,1142.850000,0,1,1,1
190,2008,0.750000,60000,0,1506.000000,0,1,1,1
191,2012,0.570000,25000,1,1146.840000,0,1,1,1
192,2007,0.750000,49000,1,1505.250000,0,1,1,1
193,2013,0.650000,24000,1,1308.450000,0,1,1,1
194,2008,0.787000,50000,0,1580.296000,0,1,1,1
195,2015,0.320000,35000,0,644.800000,0,1,1,1
196,2008,0.520000,500000,0,1044.160000,0,1,1,0
197,2010,0.510000,33000,0,1025.100000,0,1,1,1
198,2011,0.570000,35000,1,1146.270000,0,1,1,1
199,2007,0.580000,53000,0,1164.060000,0,1,1,1
200,2006,0.750000,92233,0,1504.500000,0,1,1,1
201,2010,6.790000,58000,1,13647.900000,1,0,0,1
202,2015,5.700000,28200,0,11485.500000,0,1,0,1
203,2011,4.600000,53460,0,9250.600000,0,1,0,1
204,2015,4.430000,28282,0,8926.450000,0,1,0,1
205,2016,5.700000,3493,1,11491.200000,0,1,0,1
206,2017,7.130000,12479,0,14381.210000,0,1,0,1
207,2015,5.700000,34797,0,11485.500000,0,1,0,0
208,2017,8.100000,3435,0,16337.700000,0,1,0,1
209,2015,5.700000,21125,0,11485.500000,1,0,0,1
210,2012,4.600000,35775,0,9255.200000,0,1,0,1
211,2015,14.790000,43535,0,29801.850000,1,0,0,1
212,2016,13.600000,22671,0,27417.600000,0,1,0,1
213,2011,6.790000,31604,0,13654.690000,0,1,0,1
214,2017,5.700000,20114,0,11496.900000,0,1,0,1
215,2012,9.400000,36100,0,18912.800000,0,1,0,1
216,2016,4.430000,12500,0,8930.880000,0,1,0,1
217,2016,4.430000,15000,0,8930.880000,0,1,0,1
218,2014,9.400000,45078,0,18931.600000,0,1,0,1
219,2012,9.400000,36000,0,18912.800000,0,1,0,1
220,2017,4.430000,38488,0,8935.310000,0,1,0,1
221,2013,6.790000,32000,0,13668.270000,0,1,0,0
222,2014,7.600000,77632,0,15306.400000,1,0,0,1
223,2015,9.400000,61381,0,18941.000000,1,0,0,1
224,2013,9.400000,36198,0,18922.200000,0,1,0,0
225,2011,4.600000,22517,0,9250.600000,0,1,0,1
226,2015,5.700000,24678,0,11485.500000,0,1,0,1
227,2011,4.430000,57000,0,8908.730000,0,1,0,1
228,2012,9.400000,60000,0,18912.800000,1,0,0,1
229,2012,6.790000,52132,0,13661.480000,1,0,0,1
230,2013,9.400000,45000,0,18922.200000,1,0,0,1
231,2017,9.400000,15001,0,18959.800000,0,1,0,1
232,2015,14.790000,12900,0,29801.850000,0,1,0,0
233,2013,5.700000,53000,0,11474.100000,1,0,0,1
234,2015,5.700000,4492,0,11485.500000,0,1,0,1
235,2017,9.400000,15141,0,18959.800000,0,1,0,1
236,2016,4.430000,11849,0,8930.880000,0,1,0,1
237,2015,13.600000,68000,0,27404.000000,1,0,0,1
238,2013,9.400000,60241,0,18922.200000,0,1,0,1
239,2012,4.430000,23709,0,8913.160000,0,1,0,1
240,2012,9.400000,32322,0,18912.800000,1,0,0,1
241,2015,7.130000,35866,1,14366.950000,0,1,0,1
242,2014,7.130000,34000,0,14359.820000,0,1,0,1
243,2016,7.600000,7000,0,15321.600000,0,1,0,1
244,2013,9.400000,49000,0,18922.200000,1,0,0,1
245,2012,9.400000,71000,0,18912.800000,1,0,0,1
246,2012,6.790000,35000,0,13661.480000,0,1,0,1
247,2015,9.400000,36000,0,18941.000000,0,1,0,1
248,2013,4.600000,30000,0,9259.800000,0,1,0,1
249,2016,7.600000,17000,0,15321.600000,0,1,0,1
250,2016,13.600000,35934,0,27417.600000,1,0,0,1
251,2013,9.900000,56701,0,19928.700000,0,1,0,1
252,2015,6.820000,31427,0,13742.300000,0,1,0,0
253,2014,9.900000,48000,0,19938.600000,1,0,0,1
254,2013,9.900000,54242,0,19928.700000,0,1,0,1
255,2012,5.350000,53675,0,10764.200000,0,1,0,1
256,2016,13.600000,49562,0,27417.600000,0,1,0,1
257,2015,13.600000,40324,0,27404.000000,0,1,0,1
258,2015,13.600000,25000,0,27404.000000,0,1,0,1
259,2014,7.000000,36054,0,14098.000000,0,1,0,1
260,2016,13.600000,29223,0,27417.600000,0,1,0,1
261,2016,5.970000,5600,0,12035.520000,0,1,0,1
262,2015,5.800000,40023,0,11687.000000,0,1,0,1
263,2016,7.700000,16002,0,15523.200000,0,1,0,1
264,2015,7.000000,40026,0,14105.000000,0,1,0,1
265,2017,8.700000,21200,0,17547.900000,0,1,0,1
266,2014,7.000000,35000,0,14098.000000,0,1,0,1
267,2016,9.400000,19434,0,18950.400000,1,0,0,1
268,2017,5.800000,19000,0,11698.600000,0,1,0,1
269,2015,10.000000,18828,0,20150.000000,0,1,0,1
270,2011,10.000000,69341,0,20110.000000,0,1,0,1
271,2009,10.000000,69562,0,20090.000000,0,1,0,1
272,2015,10.000000,27600,0,20150.000000,0,1,0,1
273,2010,7.500000,61203,0,15075.000000,0,1,0,1
274,2014,6.800000,16500,0,13695.200000,0,1,0,1
275,2016,13.600000,30753,0,27417.600000,0,1,0,0
276,2015,13.600000,24800,0,27404.000000,0,1,0,1
277,2015,13.600000,21780,0,27404.000000,0,1,0,1
278,2016,8.400000,4000,0,16934.400000,0,1,0,1
279,2014,13.600000,40126,0,27390.400000,0,1,0,1
280,2015,5.900000,14465,0,11888.500000,0,1,0,1
281,2006,7.600000,50456,0,15245.600000,0,1,0,1
282,2014,14.000000,63000,0,28196.000000,1,0,0,1
283,2016,11.800000,9010,0,23788.800000,0,1,0,1
284,2013,5.900000,9800,0,11876.700000,0,1,0,1
285,2016,8.500000,15059,0,17136.000000,0,1,0,0
286,2016,7.900000,28569,0,15926.400000,0,1,0,1
287,2015,7.500000,44000,0,15112.500000,0,1,0,0
288,2015,13.600000,34000,0,27404.000000,0,1,0,1
289,2016,13.600000,10980,0,27417.600000,0,1,0,1
290,2014,6.400000,19000,0,12889.600000,0,1,0,1
291,2015,6.100000,31427,0,12291.500000,0,1,0,1
292,2016,8.400000,12000,0,16934.400000,0,1,0,1
293,2010,9.900000,38000,0,19899.000000,0,1,0,1
294,2014,6.800000,33019,0,13695.200000,0,1,0,1
295,2015,13.090000,60076,0,26376.350000,1,0,0,1
296,2016,11.600000,33988,0,23385.600000,1,0,0,1
297,2015,5.900000,60000,0,11888.500000,0,1,0,1
298,2009,11.000000,87934,0,22099.000000,0,1,0,1
299,2017,12.500000,9000,0,25212.500000,1,0,0,1
300,2016,5.900000,5464,0,11894.400000,0,1,0,1

In [41]:
# type your code here
y = df['Selling_Price'] 
x = pd.get_dummies(df_['Fuel_Type'],drop_first = True)
z = pd.get_dummies(df_['Seller_Type'],drop_first= True)
r = pd.get_dummies(df_['Transmission'],drop_first=True)
df_['add'] = df_s['Year'] + df_s['Present_Price'] + df_s['Kms_Driven'] + df_s['Owner'] + x + z + r

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices